services:
  database:
    image: mongo:latest
    container_name: mongodb_ixc_chat
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat_app
    restart: always
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://root:password@database:27017/ixc_chat?authSource=admin
    depends_on:
      - database

volumes:
  mongo-data:
